import {
	APIApplicationCommandInteractionDataBasicOption,
	APIApplicationCommandInteractionDataOption,
	APIApplicationCommandInteractionDataSubcommandOption,
	APIInteractionResponse,
	APIModalSubmission,
	InteractionResponseType,
} from 'discord-api-types/v10';

export const mapFiles = <T>(context: __WebpackModuleApi.RequireContext) =>
	context.keys().map<T>((path) => context(path).command);

export const deferUpdate = (): APIInteractionResponse => ({
	type: InteractionResponseType.DeferredMessageUpdate,
});

export const getOption = <
	T extends
		| string
		| number
		| boolean
		| APIApplicationCommandInteractionDataBasicOption[]
		| APIApplicationCommandInteractionDataSubcommandOption[]
>(
	options: APIApplicationCommandInteractionDataOption[] | undefined,
	name: string
): T | undefined => {
	const option = options?.find((option) => option.name === name);

	// @ts-expect-error
	return option && ('value' in option ? option.value : option.options);
};

export const getModalValue = (data: APIModalSubmission, name: string) => {
	const row = data.components?.find(({ components }) => components[0].custom_id === name);

	return row?.components[0].value;
};

export const supportedRuntimes = {
	languages: new Set([
		'matl',
		'bash',
		'befunge93',
		'brachylog',
		'brainfuck',
		'cjam',
		'clojure',
		'cobol',
		'coffeescript',
		'cow',
		'crystal',
		'dart',
		'dash',
		'typescript',
		'javascript',
		'basic.net',
		'fsharp.net',
		'csharp.net',
		'fsi',
		'dragon',
		'elixir',
		'emacs',
		'emojicode',
		'erlang',
		'file',
		'forte',
		'forth',
		'freebasic',
		'awk',
		'c',
		'c++',
		'd',
		'fortran',
		'go',
		'golfscript',
		'groovy',
		'haskell',
		'husk',
		'iverilog',
		'japt',
		'java',
		'jelly',
		'julia',
		'kotlin',
		'lisp',
		'llvm_ir',
		'lolcode',
		'lua',
		'csharp',
		'basic',
		'nasm',
		'nasm64',
		'nim',
		'javascript',
		'ocaml',
		'octave',
		'osabie',
		'paradoc',
		'pascal',
		'perl',
		'php',
		'ponylang',
		'prolog',
		'pure',
		'powershell',
		'pyth',
		'python2',
		'python',
		'racket',
		'raku',
		'retina',
		'rockstar',
		'rscript',
		'ruby',
		'rust',
		'scala',
		'smalltalk',
		'sqlite3',
		'swift',
		'typescript',
		'vlang',
		'vyxal',
		'yeethon',
		'zig',
	]),
	aliases: new Set([
		'sh',
		'b93',
		'bf',
		'clojure',
		'clj',
		'cob',
		'coffeescript',
		'coffee',
		'cow',
		'crystal',
		'cr',
		'dash',
		'deno',
		'deno-ts',
		'deno-js',
		'basic',
		'visual-basic',
		'visual-basic.net',
		'vb',
		'vb.net',
		'vb-dotnet',
		'dotnet-vb',
		'basic-dotnet',
		'dotnet-basic',
		'fsharp',
		'fs',
		'f#',
		'fs.net',
		'f#.net',
		'fsharp-dotnet',
		'fs-dotnet',
		'f#-dotnet',
		'dotnet-fsharp',
		'dotnet-fs',
		'dotnet-fs',
		'csharp',
		'c#',
		'cs',
		'c#.net',
		'cs.net',
		'c#-dotnet',
		'cs-dotnet',
		'csharp-dotnet',
		'dotnet-c#',
		'dotnet-cs',
		'dotnet-csharp',
		'fsx',
		'fsharp-interactive',
		'f#-interactive',
		'dotnet-fsi',
		'fsi-dotnet',
		'fsi.net',
		'elixir',
		'exs',
		'emacs',
		'el',
		'elisp',
		'emojic',
		'erlang',
		'erl',
		'escript',
		'executable',
		'elf',
		'binary',
		'forter',
		'gforth',
		'bas',
		'fbc',
		'basic',
		'qbasic',
		'quickbasic',
		'gawk',
		'gcc',
		'cpp',
		'g++',
		'gdc',
		'fortran',
		'f90',
		'go',
		'golang',
		'golfscript',
		'groovy',
		'gvy',
		'haskell',
		'hs',
		'verilog',
		'vvp',
		'japt',
		'jl',
		'kt',
		'lisp',
		'cl',
		'sbcl',
		'commonlisp',
		'llvm',
		'llvm-ir',
		'll',
		'lol',
		'lci',
		'lua',
		'mono',
		'mono-csharp',
		'mono-c#',
		'mono-cs',
		'c#',
		'cs',
		'vb',
		'mono-vb',
		'mono-basic',
		'visual-basic',
		'visual basic',
		'asm',
		'nasm32',
		'asm64',
		'nim',
		'node-javascript',
		'node-js',
		'javascript',
		'js',
		'ocaml',
		'ml',
		'matlab',
		'm',
		'osabie',
		'05AB1E',
		'usable',
		'paradoc',
		'pascal',
		'freepascal',
		'pp',
		'pas',
		'perl',
		'pl',
		'php8',
		'html',
		'pony',
		'ponyc',
		'prolog',
		'plg',
		'ps',
		'pwsh',
		'ps1',
		'pyth',
		'py2',
		'python2',
		'py',
		'py3',
		'python3',
		'python3.10',
		'rkt',
		'raku',
		'rakudo',
		'perl6',
		'p6',
		'pl6',
		'ret',
		'rock',
		'rocky',
		'r',
		'ruby3',
		'rb',
		'rs',
		'sc',
		'st',
		'sqlite',
		'sql',
		'swift',
		'ts',
		'node-ts',
		'tsc',
		'v',
		'yeethon3',
		'zig',
	]),
};

export const supportedMarkdown: Record<string, string> = {
	'1c': '1C',
	'4d': '4D',
	'sap-abap': 'ABAP',
	abap: 'ABAP',
	abnf: 'ABNF',
	accesslog: 'Access logs',
	ada: 'Ada',
	apex: 'Apex',
	arduino: 'Arduino',
	ino: 'Arduino',
	armasm: 'ARM assembler',
	arm: 'ARM assembler',
	avrasm: 'AVR assembler',
	actionscript: 'ActionScript',
	as: 'ActionScript',
	alan: 'Alan IF',
	i: 'Alan IF',
	ln: 'Alan',
	angelscript: 'AngelScript',
	asc: 'AngelScript',
	apache: 'Apache',
	apacheconf: 'Apache',
	applescript: 'AppleScript',
	osascript: 'AppleScript',
	arcade: 'Arcade',
	asciidoc: 'AsciiDoc',
	adoc: 'AsciiDoc',
	aspectj: 'AspectJ',
	autohotkey: 'AutoHotkey',
	autoit: 'AutoIt',
	awk: 'Awk',
	mawk: 'Awk',
	nawk: 'Awk',
	gawk: 'Awk',
	bash: 'Bash',
	sh: 'Bash',
	zsh: 'Bash',
	basic: 'Basic',
	bbcode: 'BBCode',
	blade: 'Blade',
	bnf: 'BNF',
	brainfuck: 'Brainfuck',
	bf: 'Brainfuck',
	csharp: 'C#',
	cs: 'C#',
	c: 'C',
	h: 'C',
	cpp: 'C++',
	hpp: 'C++',
	cc: 'C++',
	hh: 'C++',
	'c++': 'C++',
	'h++': 'C++',
	cxx: 'C++',
	hxx: 'C++',
	cal: 'C/AL',
	cos: 'Cache Object Script',
	cls: 'Cache Object Script',
	cmake: 'CMake',
	'cmake.in': 'CMake',
	cobol: 'COBOL',
	'standard-cobol': 'COBOL',
	coq: 'Coq',
	csp: 'CSP',
	css: 'CSS',
	capnproto: "Cap'n Proto",
	capnp: "Cap'n Proto",
	chaos: 'Chaos',
	kaos: 'Chaos',
	chapel: 'Chapel',
	chpl: 'Chapel',
	cisco: 'Cisco CLI',
	clojure: 'Clojure',
	clj: 'Clojure',
	coffeescript: 'CoffeeScript',
	coffee: 'CoffeeScript',
	cson: 'CoffeeScript',
	iced: 'CoffeeScript',
	cpc: 'CpcdosC+',
	crmsh: 'Crmsh',
	crm: 'Crmsh',
	pcmk: 'Crmsh',
	crystal: 'Crystal',
	cr: 'Crystal',
	curl: 'cURL',
	cypher: '',
	d: 'D',
	dafny: 'Dafny',
	dart: 'Dart',
	dpr: 'Delphi',
	dfm: 'Delphi',
	pas: 'Delphi',
	pascal: 'Delphi',
	diff: 'Diff',
	patch: 'Diff',
	django: 'Django',
	jinja: 'Django',
	dns: 'DNS Zone file',
	zone: 'DNS Zone file',
	bind: 'DNS Zone file',
	dockerfile: 'Dockerfile',
	docker: 'Dockerfile',
	dos: 'DOS',
	bat: 'DOS',
	cmd: 'DOS',
	dsconfig: 'dsconfig',
	dts: 'DTS',
	dust: 'Dust',
	dst: 'Dust',
	dylan: 'Dylan',
	ebnf: 'EBNF',
	elixir: 'Elixir',
	elm: 'Elm',
	erlang: 'Erlang',
	erl: 'Erlang',
	excel: 'Excel',
	xls: 'Excel',
	xlsx: 'Excel',
	extempore: 'Extempore',
	xtlang: 'Extempore',
	xtm: 'Extempore',
	fsharp: 'F#',
	fs: 'F#',
	fix: 'FIX',
	fortran: 'Fortran',
	f90: 'Fortran',
	f95: 'Fortran',
	gcode: 'G-Code',
	nc: 'G-Code',
	gams: 'Gams',
	gms: 'Gams',
	gauss: 'GAUSS',
	gss: 'GAUSS',
	godot: 'GDScript',
	gdscript: 'GDScript',
	gherkin: 'Gherkin',
	hbs: 'Handlebars',
	glimmer: 'Glimmer and EmberJS',
	'html.hbs': 'Handlebars',
	'html.handlebars': 'Handlebars',
	htmlbars: 'Glimmer and EmberJS',
	gn: 'GN for Ninja',
	gni: 'GN for Ninja',
	go: 'Go',
	golang: 'Go',
	gf: 'Grammatical Framework',
	golo: 'Golo',
	gololang: 'Golo',
	gradle: 'Gradle',
	graphql: 'GraphQL',
	groovy: 'Groovy',
	gsql: 'GSQL',
	xml: 'HTML, XML',
	html: 'HTML, XML',
	xhtml: 'HTML, XML',
	rss: 'HTML, XML',
	atom: 'HTML, XML',
	xjb: 'HTML, XML',
	xsd: 'HTML, XML',
	xsl: 'HTML, XML',
	plist: 'HTML, XML',
	svg: 'HTML, XML',
	http: 'HTTP',
	https: 'HTTP',
	haml: 'Haml',
	handlebars: 'Handlebars',
	haskell: 'Haskell',
	hs: 'Haskell',
	haxe: 'Haxe',
	hx: 'Haxe',
	hlsl: 'High-level shader language',
	hy: 'Hy',
	hylang: 'Hy',
	ini: 'Ini, TOML',
	toml: 'Ini, TOML',
	inform7: 'Inform7',
	i7: 'Inform7',
	irpf90: 'IRPF90',
	json: 'JSON',
	java: 'Java',
	jsp: 'Java',
	javascript: 'JavaScript',
	js: 'JavaScript',
	jsx: 'JavaScript',
	jolie: 'Jolie',
	iol: 'Jolie',
	ol: 'Jolie',
	julia: 'Julia',
	'julia-repl': 'Julia',
	kotlin: 'Kotlin',
	kt: 'Kotlin',
	tex: 'LaTeX',
	leaf: 'Leaf',
	lean: 'Lean',
	lasso: 'Lasso',
	ls: 'LiveScript',
	lassoscript: 'Lasso',
	less: 'Less',
	ldif: 'LDIF',
	lisp: 'Lisp',
	livecodeserver: 'LiveCode Server',
	livescript: 'LiveScript',
	lua: 'Lua',
	macaulay2: 'Macaulay2',
	makefile: 'Makefile',
	mk: 'Makefile',
	mak: 'Makefile',
	make: 'Makefile',
	markdown: 'Markdown',
	md: 'Markdown',
	mkdown: 'Markdown',
	mkd: 'Markdown',
	mathematica: 'Mathematica',
	mma: 'Mathematica',
	wl: 'Mathematica',
	matlab: 'Matlab',
	maxima: 'Maxima',
	mel: 'Maya Embedded Language',
	mercury: 'Mercury',
	mirc: 'mIRC Scripting Language',
	mrc: 'mIRC Scripting Language',
	mizar: 'Mizar',
	mkb: 'MKB',
	mlir: 'MLIR',
	mojolicious: 'Mojolicious',
	monkey: 'Monkey',
	moonscript: 'Moonscript',
	moon: 'Moonscript',
	n1ql: 'N1QL',
	nsis: 'NSIS',
	never: 'Never',
	nginx: 'Nginx',
	nginxconf: 'Nginx',
	nim: 'Nim',
	nimrod: 'Nim',
	nix: 'Nix',
	oak: 'Oak',
	ocl: 'Object Constraint Language',
	ocaml: 'OCaml',
	ml: 'SML',
	objectivec: 'Objective C',
	mm: 'Objective C',
	objc: 'Objective C',
	'obj-c': 'Objective C',
	'obj-c++': 'Objective C',
	'objective-c++': 'Objective C',
	glsl: 'OpenGL Shading Language',
	openscad: 'OpenSCAD',
	scad: 'OpenSCAD',
	ruleslanguage: 'Oracle Rules Language',
	oxygene: 'Oxygene',
	pf: 'PF',
	'pf.conf': 'PF',
	php: 'PHP',
	papyrus: 'Papyrus',
	psc: 'Papyrus',
	parser3: 'Parser3',
	perl: 'Perl',
	pl: 'Perl',
	pm: 'Perl',
	pine: 'Pine Script',
	pinescript: 'Pine Script',
	plaintext: 'Plaintext',
	txt: 'Plaintext',
	text: 'Plaintext',
	pony: 'Pony',
	pgsql: 'PostgreSQL & PL/pgSQL',
	postgres: 'PostgreSQL & PL/pgSQL',
	postgresql: 'PostgreSQL & PL/pgSQL',
	powershell: 'PowerShell',
	ps: 'PowerShell',
	ps1: 'PowerShell',
	processing: 'Processing',
	prolog: 'Prolog',
	properties: 'Properties',
	protobuf: 'Protocol Buffers',
	puppet: 'Puppet',
	pp: 'Puppet',
	python: 'Python',
	py: 'Python',
	gyp: 'Python',
	profile: 'Python profiler results',
	'python-repl': 'Python REPL',
	pycon: 'Python REPL',
	qsharp: 'Q#',
	k: 'Q',
	kdb: 'Q',
	qml: 'QML',
	r: 'R',
	cshtml: 'Razor CSHTML',
	razor: 'Razor CSHTML',
	'razor-cshtml': 'Razor CSHTML',
	reasonml: 'ReasonML',
	re: 'ReasonML',
	redbol: 'Rebol & Red',
	rebol: 'Rebol & Red',
	red: 'Rebol & Red',
	'red-system': 'Rebol & Red',
	rib: 'RenderMan RIB',
	rsl: 'RenderMan RSL',
	risc: 'RiScript',
	riscript: 'RiScript',
	graph: 'Roboconf',
	instances: 'Roboconf',
	robot: 'Robot Framework',
	rf: 'Robot Framework',
	'rpm-specfile': 'RPM spec files',
	rpm: 'RPM spec files',
	spec: 'RPM spec files',
	'rpm-spec': 'RPM spec files',
	specfile: 'RPM spec files',
	ruby: 'Ruby',
	rb: 'Ruby',
	gemspec: 'Ruby',
	podspec: 'Ruby',
	thor: 'Ruby',
	irb: 'Ruby',
	rust: 'Rust',
	rs: 'Rust',
	SAS: 'SAS',
	sas: 'SAS',
	scss: 'SCSS',
	sql: 'SQL',
	p21: 'STEP Part 21',
	step: 'STEP Part 21',
	stp: 'STEP Part 21',
	scala: 'Scala',
	scheme: 'Scheme',
	scilab: 'Scilab',
	sci: 'Scilab',
	shexc: 'Shape Expressions',
	shell: 'Shell',
	console: 'Shell',
	smali: 'Smali',
	smalltalk: 'Smalltalk',
	st: 'Smalltalk',
	sml: 'SML',
	solidity: 'Solidity',
	sol: 'Solidity',
	spl: 'Splunk SPL',
	stan: 'Stan',
	stanfuncs: 'Stan',
	stata: 'Stata',
	iecst: 'Structured Text',
	scl: 'Structured Text',
	stl: 'Structured Text',
	'structured-text': 'Structured Text',
	stylus: 'Stylus',
	styl: 'Stylus',
	subunit: 'SubUnit',
	supercollider: 'Supercollider',
	sc: 'Supercollider',
	svelte: 'Svelte',
	swift: 'Swift',
	tcl: 'Tcl',
	tk: 'Tcl',
	terraform: 'Terraform',
	tf: 'Terraform',
	hcl: 'Terraform',
	tap: 'Test Anything Protocol',
	thrift: 'Thrift',
	toit: 'Toit',
	tp: 'TP',
	tsql: 'Transact-SQL',
	twig: 'Twig',
	craftcms: 'Twig',
	typescript: 'TypeScript',
	ts: 'TypeScript',
	'unicorn-rails-log': 'Unicorn Rails log',
	vbnet: 'VB.Net',
	vb: 'VB.Net',
	vba: 'VBA',
	vbscript: 'VBScript',
	vbs: 'VBScript',
	vhdl: 'VHDL',
	vala: 'Vala',
	verilog: 'Verilog',
	v: 'Verilog',
	vim: 'Vim Script',
	xsharp: 'X#',
	xs: 'X#',
	prg: 'X#',
	axapta: 'X++',
	'x++': 'X++',
	x86asm: 'x86 Assembly',
	xl: 'XL',
	tao: 'XL',
	xquery: 'XQuery',
	xpath: 'XQuery',
	xq: 'XQuery',
	yml: 'YAML',
	yaml: 'YAML',
	zenscript: 'ZenScript',
	zs: 'ZenScript',
	zephir: 'Zephir',
	zep: 'Zephir',
};
