import {
	APIApplicationCommandInteractionDataBasicOption,
	APIApplicationCommandInteractionDataOption,
	APIApplicationCommandInteractionDataSubcommandOption,
	APIInteractionResponse,
	APIModalSubmission,
	InteractionResponseType,
} from 'discord-api-types/v10';
export const mapFiles = <T>(context: __WebpackModuleApi.RequireContext) =>
	context.keys().map<T>((path) => context(path).command);

export const deferUpdate = (): APIInteractionResponse => ({
	type: InteractionResponseType.DeferredMessageUpdate,
});

export const getOption = <
	T extends
		| string
		| number
		| boolean
		| APIApplicationCommandInteractionDataBasicOption[]
		| APIApplicationCommandInteractionDataSubcommandOption[]
>(
	options: APIApplicationCommandInteractionDataOption[] | undefined,
	name: string
): T | undefined => {
	const option = options?.find((option) => option.name === name);

	// @ts-expect-error
	return option && ('value' in option ? option.value : option.options);
};

export const getModalValue = (data: APIModalSubmission, name: string) => {
	const row = data.components?.find(({ components }) => components[0].custom_id === name);

	return row?.components[0].value;
};

export const supportedRuntimes = {
	languages: [
		'matl',
		'bash',
		'befunge93',
		'brachylog',
		'brainfuck',
		'cjam',
		'clojure',
		'cobol',
		'coffeescript',
		'cow',
		'crystal',
		'dart',
		'dash',
		'typescript',
		'javascript',
		'basic.net',
		'fsharp.net',
		'csharp.net',
		'fsi',
		'dragon',
		'elixir',
		'emacs',
		'emojicode',
		'erlang',
		'file',
		'forte',
		'forth',
		'freebasic',
		'awk',
		'c',
		'c++',
		'd',
		'fortran',
		'go',
		'golfscript',
		'groovy',
		'haskell',
		'husk',
		'iverilog',
		'japt',
		'java',
		'jelly',
		'julia',
		'kotlin',
		'lisp',
		'llvm_ir',
		'lolcode',
		'lua',
		'csharp',
		'basic',
		'nasm',
		'nasm64',
		'nim',
		'javascript',
		'ocaml',
		'octave',
		'osabie',
		'paradoc',
		'pascal',
		'perl',
		'php',
		'ponylang',
		'prolog',
		'pure',
		'powershell',
		'pyth',
		'python2',
		'python',
		'racket',
		'raku',
		'retina',
		'rockstar',
		'rscript',
		'ruby',
		'rust',
		'scala',
		'smalltalk',
		'sqlite3',
		'swift',
		'typescript',
		'vlang',
		'vyxal',
		'yeethon',
		'zig',
	],
	aliases: [
		'sh',
		'b93',
		'bf',
		'clojure',
		'clj',
		'cob',
		'coffeescript',
		'coffee',
		'cow',
		'crystal',
		'cr',
		'dash',
		'deno',
		'deno-ts',
		'deno-js',
		'basic',
		'visual-basic',
		'visual-basic.net',
		'vb',
		'vb.net',
		'vb-dotnet',
		'dotnet-vb',
		'basic-dotnet',
		'dotnet-basic',
		'fsharp',
		'fs',
		'f#',
		'fs.net',
		'f#.net',
		'fsharp-dotnet',
		'fs-dotnet',
		'f#-dotnet',
		'dotnet-fsharp',
		'dotnet-fs',
		'dotnet-fs',
		'csharp',
		'c#',
		'cs',
		'c#.net',
		'cs.net',
		'c#-dotnet',
		'cs-dotnet',
		'csharp-dotnet',
		'dotnet-c#',
		'dotnet-cs',
		'dotnet-csharp',
		'fsx',
		'fsharp-interactive',
		'f#-interactive',
		'dotnet-fsi',
		'fsi-dotnet',
		'fsi.net',
		'elixir',
		'exs',
		'emacs',
		'el',
		'elisp',
		'emojic',
		'erlang',
		'erl',
		'escript',
		'executable',
		'elf',
		'binary',
		'forter',
		'gforth',
		'bas',
		'fbc',
		'basic',
		'qbasic',
		'quickbasic',
		'gawk',
		'gcc',
		'cpp',
		'g++',
		'gdc',
		'fortran',
		'f90',
		'go',
		'golang',
		'golfscript',
		'groovy',
		'gvy',
		'haskell',
		'hs',
		'verilog',
		'vvp',
		'japt',
		'jl',
		'kt',
		'lisp',
		'cl',
		'sbcl',
		'commonlisp',
		'llvm',
		'llvm-ir',
		'll',
		'lol',
		'lci',
		'lua',
		'mono',
		'mono-csharp',
		'mono-c#',
		'mono-cs',
		'c#',
		'cs',
		'vb',
		'mono-vb',
		'mono-basic',
		'visual-basic',
		'visual basic',
		'asm',
		'nasm32',
		'asm64',
		'nim',
		'node-javascript',
		'node-js',
		'javascript',
		'js',
		'ocaml',
		'ml',
		'matlab',
		'm',
		'osabie',
		'05AB1E',
		'usable',
		'paradoc',
		'pascal',
		'freepascal',
		'pp',
		'pas',
		'perl',
		'pl',
		'php8',
		'html',
		'pony',
		'ponyc',
		'prolog',
		'plg',
		'ps',
		'pwsh',
		'ps1',
		'pyth',
		'py2',
		'python2',
		'py',
		'py3',
		'python3',
		'python3.10',
		'rkt',
		'raku',
		'rakudo',
		'perl6',
		'p6',
		'pl6',
		'ret',
		'rock',
		'rocky',
		'r',
		'ruby3',
		'rb',
		'rs',
		'sc',
		'st',
		'sqlite',
		'sql',
		'swift',
		'ts',
		'node-ts',
		'tsc',
		'v',
		'yeethon3',
		'zig',
	],
};
